name: QMK userspace Build
on:
  workflow_dispatch:
  push:
    paths:
      - "keyboards/**"
      - "keymaps/*"
      - ".github/workflows/*"
      - "*.def"
      - "*.c"
      - "*.h"

jobs:
  list-user-keymaps:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: echo "matrix=$(find keyboards -regex ".*keymaps" | sed "s|keyboards/\(.*\)/keymaps|\1|"| jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
      - run: echo $GITHUB_OUTPUT

  compile-qmk-user-keymaps:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    needs: list-user-keymaps
    strategy:
      fail-fast: false
      matrix:
        # keyboards: ${{ fromJson(needs.list-user-keymaps.outputs.matrix) }}
        keyboards:
          - sporkus/le_chiffre_32
    env:
      USERSPACE_PATH: users/${{ github.actor }}

    # by default, checks out to github.workspace
    # github.workspace will also be qmk_firmware root
    steps:
      - name: Checkout QMK
        uses: actions/checkout@v4
        with:
          repository: qmk/qmk_firmware
          ref: master
          submodules: true

      # path is relative to github.workspace
      - name: Checkout userspace
        uses: actions/checkout@v4
        with:
          path: ${{ env.USERSPACE_PATH }}
          persist-credentials: false

      - name: Setup safe directory
        run: git config --global --add safe.directory '*'

      - name: Install rsync
        run: apt-get update; apt-get install -y rsync

      - name: Copy users/keyboards/* to keyboards/*
        run: rsync -av ${{ env.USERSPACE_PATH }}/keyboards/ keyboards/

      - name: QMK compile
        run: qmk compile -j 0 -kb ${{ matrix.keyboards }} -km ${{ github.actor }}

      - name: Strip keyboard name
        id: keyboard-name
        run: |
          echo ${{ matrix.keyboards}} | sed "s|/|_|g"
          echo "name=${{ matrix.keyboards}}" | sed "s|/|_|g" >> $GITHUB_OUTPUT

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          retention-days: 60
          compression-level: 0
          name: qmk_${{ steps.keyboard-name.outputs.name }}
          path: |
            *.hex
            *.bin
            *.uf2

  merge:
    runs-on: ubuntu-latest
    needs: compile-qmk-user-keymaps
    steps:
      - name: qmk-user-firmware
        uses: actions/upload-artifact/merge@v4
        with:
          delete-merged: true
